[profile.default]
src = "src"
out = "out"
libs = ["node_modules", "lib"]
fs_permissions = [{ access = "read-write", path = "./src"}]

# ---
# openzepplin-upgradeable
# ---
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
# END:openzepplin-upgradeable

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
